/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PUB_SUB_DELIV_H_RPCGEN
#define _PUB_SUB_DELIV_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define POSTMESLEN 192

typedef char *postmessage;
#ifdef __cplusplus
extern "C" bool_t xdr_postmessage(XDR *, postmessage*);
#elif __STDC__
extern  bool_t xdr_postmessage(XDR *, postmessage*);
#else /* Old Style C */
bool_t xdr_postmessage();
#endif /* Old Style C */


#define PUBSUBCLTPROG ((rpc_uint)0x20000012)
#define PUBSUBCLTVERS ((rpc_uint)1)

#ifdef __cplusplus
#define deliver ((rpc_uint)1)
extern "C" void * deliver_1(postmessage *, CLIENT *);
extern "C" void * deliver_1_svc(postmessage *, struct svc_req *);

#elif __STDC__
#define deliver ((rpc_uint)1)
extern  void * deliver_1(postmessage *, CLIENT *);
extern  void * deliver_1_svc(postmessage *, struct svc_req *);

#else /* Old Style C */
#define deliver ((rpc_uint)1)
extern  void * deliver_1();
extern  void * deliver_1_svc();
#endif /* Old Style C */

#endif /* !_PUB_SUB_DELIV_H_RPCGEN */
