/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PUB_SUB_H_RPCGEN
#define _PUB_SUB_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define TOPLEN 64
#define MESLEN 128

typedef char *topic;
#ifdef __cplusplus
extern "C" bool_t xdr_topic(XDR *, topic*);
#elif __STDC__
extern  bool_t xdr_topic(XDR *, topic*);
#else /* Old Style C */
bool_t xdr_topic();
#endif /* Old Style C */


typedef char *message;
#ifdef __cplusplus
extern "C" bool_t xdr_message(XDR *, message*);
#elif __STDC__
extern  bool_t xdr_message(XDR *, message*);
#else /* Old Style C */
bool_t xdr_message();
#endif /* Old Style C */


#define PUBSUBPROG ((rpc_uint)0x20000011)
#define PUBSUBVERS ((rpc_uint)1)

#ifdef __cplusplus
#define set_channel ((rpc_uint)1)
extern "C" short * set_channel_1(topic *, CLIENT *);
extern "C" short * set_channel_1_svc(topic *, struct svc_req *);
#define subscribe ((rpc_uint)2)
extern "C" short * subscribe_1(void *, CLIENT *);
extern "C" short * subscribe_1_svc(void *, struct svc_req *);
#define unsubscribe ((rpc_uint)3)
extern "C" short * unsubscribe_1(void *, CLIENT *);
extern "C" short * unsubscribe_1_svc(void *, struct svc_req *);
#define publish ((rpc_uint)4)
extern "C" short * publish_1(message *, CLIENT *);
extern "C" short * publish_1_svc(message *, struct svc_req *);

#elif __STDC__
#define set_channel ((rpc_uint)1)
extern  short * set_channel_1(topic *, CLIENT *);
extern  short * set_channel_1_svc(topic *, struct svc_req *);
#define subscribe ((rpc_uint)2)
extern  short * subscribe_1(void *, CLIENT *);
extern  short * subscribe_1_svc(void *, struct svc_req *);
#define unsubscribe ((rpc_uint)3)
extern  short * unsubscribe_1(void *, CLIENT *);
extern  short * unsubscribe_1_svc(void *, struct svc_req *);
#define publish ((rpc_uint)4)
extern  short * publish_1(message *, CLIENT *);
extern  short * publish_1_svc(message *, struct svc_req *);

#else /* Old Style C */
#define set_channel ((rpc_uint)1)
extern  short * set_channel_1();
extern  short * set_channel_1_svc();
#define subscribe ((rpc_uint)2)
extern  short * subscribe_1();
extern  short * subscribe_1_svc();
#define unsubscribe ((rpc_uint)3)
extern  short * unsubscribe_1();
extern  short * unsubscribe_1_svc();
#define publish ((rpc_uint)4)
extern  short * publish_1();
extern  short * publish_1_svc();
#endif /* Old Style C */

#endif /* !_PUB_SUB_H_RPCGEN */
