/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pub_sub.h"

bool_t
xdr_topic(xdrs, objp)
	XDR *xdrs;
	topic *objp;
{

	if (!xdr_string(xdrs, objp, TOPLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_message(xdrs, objp)
	XDR *xdrs;
	message *objp;
{

	if (!xdr_string(xdrs, objp, MESLEN))
		return (FALSE);
	return (TRUE);
}
