/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pub_sub_deliv.h"

bool_t
xdr_postmessage(xdrs, objp)
	XDR *xdrs;
	postmessage *objp;
{

	if (!xdr_string(xdrs, objp, POSTMESLEN))
		return (FALSE);
	return (TRUE);
}
