/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pub_sub.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

short *
set_channel_1(argp, clnt)
	topic *argp;
	CLIENT *clnt;
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, set_channel, xdr_topic, argp, xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

short *
subscribe_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, subscribe, xdr_void, argp, xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

short *
unsubscribe_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, unsubscribe, xdr_void, argp, xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

short *
publish_1(argp, clnt)
	message *argp;
	CLIENT *clnt;
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, publish, xdr_message, argp, xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
